-- AlterTable
ALTER TABLE `Message`
  ADD COLUMN `kind` ENUM('TEXT', 'IMAGE', 'FILE') NOT NULL DEFAULT 'TEXT',
  ADD COLUMN `fileName` VARCHAR(191) NULL,
  ADD COLUMN `storedName` VARCHAR(191) NULL,
  ADD COLUMN `mimeType` VARCHAR(191) NULL,
  ADD COLUMN `fileSize` INTEGER NULL,
  MODIFY `content` VARCHAR(191) NOT NULL DEFAULT '';
